name: flutter_web_bluetooth
description: A library to use the web bluetooth api in your web project. Will play nice if used in IO projects.
version: 0.2.0
homepage: https://github.com/jeroen1602/flutter_web_bluetooth/
repository: https://github.com/jeroen1602/flutter_web_bluetooth/
issue_tracker: https://github.com/jeroen1602/flutter_web_bluetooth/issues/

environment:
  sdk: ">=2.17.0 <3.0.0"

platforms:
  web:

dependencies:
  js: ">=0.6.3 <0.7.0"
  logging: ^1.0.0
  meta: ">=1.3.0 <1.10.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
