name: flutter_web_bluetooth
description: A library to use the web bluetooth api in your web project. Will play nice if used IO projects.
version: 0.0.5
homepage: https://github.com/jeroen1602/flutter_web_bluetooth/
repository: https://github.com/jeroen1602/flutter_web_bluetooth/
issue_tracker: https://github.com/jeroen1602/flutter_web_bluetooth/issues/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: '>=0.6.3 <0.7.0'
  meta: ^1.7.0

dev_dependencies:
  test: ^1.17.4
  lints: ^1.0.0
